# Generated by Django 4.2.5 on 2023-09-09 22:45

from django.db import migrations, models
import endpointapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_name', models.CharField(max_length=50)),
                ('current_day', models.DateField(default=endpointapp.models.days)),
                ('utc_time', models.DateTimeField(verbose_name='2023-09-09T22:45:32Z')),
                ('track', models.CharField(max_length=50)),
                ('github_file_url', models.CharField(max_length=200)),
                ('gitup_repo_url', models.CharField(max_length=200)),
                ('status_code', models.IntegerField(default=200)),
            ],
        ),
    ]
