# Generated by Django 4.2.5 on 2023-09-10 11:10

from django.db import migrations, models
import endpointapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='current_day',
            field=models.DateField(default=endpointapp.models.days, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='utc_time',
            field=models.DateTimeField(verbose_name='2023-09-10T11:10:48Z'),
        ),
    ]
