# Generated by Django 4.2.5 on 2023-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointapp', '0003_alter_endpoint_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='utc_time',
            field=models.DateTimeField(verbose_name='2023-09-10T13:47:03Z'),
        ),
    ]
