# Generated by Django 4.2.5 on 2023-09-10 14:29

from django.db import migrations, models
import endpointapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointapp', '0004_alter_endpoint_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='utc_time',
            field=models.DateTimeField(default=endpointapp.models.default_utc_time),
        ),
    ]
